import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from matplotlib.lines import Line2D
import ast
import pandas as pd
import numpy as np
import math
from collections import defaultdict
from Codes.evaluation import draw_lineplots


main_colours = {"UTR": "gray", "interaction" : "red", "subopt": "orange", "MEME": "red"}
CDS_colours = defaultdict(lambda:"black")
for k, v in [("ISFV","m"), ("cISFVG","m"), ("dISFVG","plum"),("MBFV","blue"),("NKV","green"),("TBFV","c")]:
    CDS_colours[k] = v
linewidths = {"UTR": 4,
              "CDS": 4,
              "CMHit": 8,
              "Subopt": 4,
              "Interaction": 4,
              "MEME": 16,
              }

def draw_extra_lineplot(df, meme_sites, extra_bases_roi, output, virus_class):
    """
    Draw an interaction lineplot 
    showcasing interaction position relative to UTR/CDS.
    
    df (df): the dataframe outputted by main_intarna.
    meme_sites (dict): Dictionary of meme sites. generated by meme_to_lineplot.
                       Note: Give the class specific dict here not the mega dict!
                       (e.g.: mega_dict[virus_class])
    extra_bases_roi (int): Amount of extra bases from the CDS used on each side
    output (str): Filepath where the plot should be saved
    virus_class (str): Name of the given virus class
    """
    plt.style.use("seaborn-v0_8-darkgrid")
    fig, (side5, side3) = plt.subplots(2, figsize=(16, 20))

    for index, row in df.iterrows():
        t_tuple = ast.literal_eval(row["t_inter_range"])
        q_tuple = ast.literal_eval(row["q_inter_range"])
        line5sub = []
        line3sub = []
        ## Plot CDS:
        ## Differentiate between cISFVG and dISFVG
        cds_colour = CDS_colours[row["type"]] if row["class"] == "ISFV" else  CDS_colours[row["class"]]
        side5.plot((0, extra_bases_roi), (index, index), 
                   linewidth=linewidths["CDS"], color=cds_colour, solid_capstyle="butt")
        side3.plot((0 - row["UTR3len"], -extra_bases_roi - row["UTR3len"]), (index, index), 
                   linewidth=linewidths["CDS"], color=cds_colour, solid_capstyle="butt")
        ## Plot UTR:
        side5.plot((0, -row["UTR5len"]), (index, index), 
                   linewidth=linewidths["UTR"], color=main_colours["UTR"], solid_capstyle="butt")
        side3.plot((0 - row["UTR3len"], 0), (index, index), 
                   linewidth=linewidths["UTR"], color=main_colours["UTR"], solid_capstyle="butt")
        ## Plot CM hits:
        if "cm_hit_f" in row and not math.isnan(row["cm_hit_f"]):
            side3.plot((row["cm_hit_f"] - row["UTR3len"], row["cm_hit_t"] - row["UTR3len"]), (index, index), 
                       linewidth=linewidths["CMHit"], color=CDS_colours[row["cm_hit_src"]], alpha=0.5, solid_capstyle="butt")
        ## Plot Subopt Interactions:
        for suboptt in ast.literal_eval(row["suboptts"]): ## 5' Subopt stuff..
            if suboptt:
                for subopt in suboptt:
                    side5.plot((subopt[0], subopt[1]), (index, index), 
                               linewidth=linewidths["Subopt"], color=main_colours["subopt"], solid_capstyle="butt")
        for suboptq in ast.literal_eval(row["suboptqs"]): ## 3' Subopt stuff..
            if suboptq:
                for subopt in suboptq:
                    side3.plot((subopt[0] - row["UTR3len"], subopt[1] - row["UTR3len"]), (index, index), 
                               linewidth=linewidths["Subopt"], color=main_colours["subopt"], solid_capstyle="butt")
        ## Plot Main Interactions:
        side5.plot((t_tuple[0], t_tuple[1]), (index, index), 
                   linewidth=linewidths["Interaction"], color=main_colours["interaction"], solid_capstyle="butt")
        side3.plot((q_tuple[0] - row["UTR3len"], q_tuple[1] - row["UTR3len"]), (index, index), 
                   linewidth=linewidths["Interaction"], color=main_colours["interaction"], solid_capstyle="butt")
        ## Plot MEME sites:
        ## Plot Site 1:
        if row["id"] in meme_sites["site_1"]:
            site1 = meme_sites["site_1"][row["id"]]
            site1_area_start = -40
            site1_tuple = (site1_area_start + site1[0], site1_area_start + site1[1]) 
            side5.plot(site1_tuple, (index, index),  linewidth=linewidths["MEME"],
                       color=main_colours["MEME"],  alpha=0.3,  solid_capstyle="butt")
        ## Plot Site 2:
        if row["id"] in meme_sites["site_2"]:
            site2 = meme_sites["site_2"][row["id"]]
            site2_area_start = 20
            site2_tuple = (site2_area_start + site2[0], site2_area_start + site2[1])
            side5.plot(site2_tuple, (index, index),  linewidth=linewidths["MEME"],
                       color=main_colours["MEME"],  alpha=0.3,  solid_capstyle="butt")
        ## Plot Site 3:
        if row["id"] in meme_sites["site_3"]:
            CMhit_start = row["cm_hit_f"] - row["UTR3len"]
            site3 = meme_sites["site_3"][row["id"]]
            site3_area_start = CMhit_start-25
            site3_tuple = (site3_area_start + site3[0], site3_area_start + site3[1])
            side3.plot(site3_tuple, (index, index),  linewidth=linewidths["MEME"],
                       color=main_colours["MEME"],  alpha=0.3,  solid_capstyle="butt")
        ## Plot Site 4:
        if row["id"] in meme_sites["site_4"]:
            CMhit_start = row["cm_hit_f"] - row["UTR3len"]
            site4 = meme_sites["site_4"][row["id"]]
            site4_area_start = CMhit_start+5
            site4_tuple = (site4_area_start + site4[0], site4_area_start + site4[1])
            side3.plot(site4_tuple, (index, index),  linewidth=linewidths["MEME"],
                       color=main_colours["MEME"],  alpha=0.3, solid_capstyle="butt")

    ## Annotations:
    side5.set_xlabel("Distance from 5'UTR-CDS transition", fontsize=16)
    side3.set_xlabel("Distance from 3'UTR end", fontsize=16)
    side5.set_ylabel("Index", fontsize=16)
    side3.set_ylabel("Index", fontsize=16)
    side5.yaxis.set_label_position("right")
    side5.yaxis.tick_right()
    side3.yaxis.set_label_position("right")
    side3.yaxis.tick_right()

    side5.set_yticks(np.arange(len(df["id"])))
    side5.set_yticklabels(list(df["id"]))
    side3.set_yticks(np.arange(len(df["id"])))
    side3.set_yticklabels(list(df["id"]))
    side5.autoscale_view()
    side3.autoscale_view()
    legend_elements = [Line2D([0], [0], color=CDS_colours[virus_class], lw=8, label=f"{virus_class}-CDS"),
                       Line2D([0], [0], color='gray', lw=8, label='UTR'),
                       Line2D([0], [0], color='r', lw=8, label='Interaction'),
                       Line2D([0], [0], color='orange', lw=8, label='Subopt'),
                       Line2D([0], [0], color='r', alpha=0.3, lw=linewidths["MEME"], label='MEME Hit'),
                       Line2D([0], [0], color="blue", lw=8, label='CM Hit', alpha=0.5),]
    if virus_class == "ISFV":
        legend_elements = [Line2D([0], [0], color=CDS_colours["cISFVG"], lw=8, label=f"{'cISFV'}-CDS"),
                           Line2D([0], [0], color=CDS_colours["dISFVG"], lw=8, label=f"{'dISFV'}-CDS")] + legend_elements[1:]
    side5.legend(handles=legend_elements[:-1],loc="upper left", prop={"size": 16})
    side3.legend(handles=legend_elements,loc="upper left", prop={"size": 16})
    plt.suptitle(f"Interaction Lineplot {virus_class}", fontsize=48)
    plt.savefig(output)
    plt.close()

def meme_to_lineplot(df, extra_bases_roi, meme_output):
    """Improvised function to extract relevant information from meme output text files
    to add them to a lineplot similar to the one from evaluation.py.
    Noteworth variables:
    mega_dict(dict): A dictionary of virus classes where each entry is a
                     dictionary of the 4 sites and their respective motifs
                     locations for each of the sequences as tuples.
                     {"class": {"site": {"id" : (motif_start, motif_end)}}}
    """
    virus_classes = ("MBFV", "TBFV", "ISFV", "NKV")
    mega_dict = defaultdict(dict)
    for site in ["site_1", "site_2", "site_3", "site_4"]:
        d = defaultdict(dict)
        f = open(f"{meme_output}/MEME Outputs/{site}/meme.txt", "r")
        trigger = False
        for l in f.readlines():
            if l.startswith("Sequence name             Start   P-value                    Site"):
                trigger = True
            elif trigger and l.startswith(virus_classes):
                l_split = l.split()
                l_split0_split = l_split[0].split("-")
                motif_start = int(l_split[1])
                motif_end = motif_start + len(l_split[4])
                id = l_split0_split[1]
                # if l_split[2].split("-")[1] > THRESHOLD: ## has form of "8.92e-11"
                d[l_split0_split[0]][id] = (motif_start, motif_end)
            elif trigger and l.startswith("--------------"):
                break
        for virus_class in virus_classes:
            mega_dict[virus_class][site] = d[virus_class]
    for virus_class in virus_classes:
        meme_sites = mega_dict[virus_class]
        draw_lineplots(df.loc[df["class"] == virus_class],
                       extra_bases_roi,
                       f"{meme_output}/MEME_{virus_class}.png", subopt_mode=True, meme_sites=meme_sites) #virus_class ? 
 
    
def glam2_to_lineplot(df, extra_bases_roi, meme_output):
    """
    Improvised function to extract relevant information from glam2 output text files
    to add them to a lineplot similar to the one from evaluation.py.
    Note: This will literally only work with the super specific output file by the MEME Suite webserver.
    Noteworth variables:
    mega_dict(dict): A dictionary of virus classes where each entry is a
                     dictionary of the 4 sites and their respective motifs
                     locations for each of the sequences as tuples.
                     {"class": {"site": {"id" : (motif_start, motif_end)}}}
    """
    from Bio import SeqIO ### ...
    virus_classes = ("MBFV", "TBFV", "ISFV", "NKV")
    mega_dict = defaultdict(dict)
    for site in ["site_1", "site_2", "site_3", "site_4"]:
        seq_dict = {str(rec.seq) : rec.id for rec in SeqIO.parse(f"{meme_output}/{site}.fa", "fasta")} ### ...
        d = defaultdict(dict)
        f = open(f"{meme_output}/GLAM2 Outputs/{site}/glam2.txt", "r")
        trigger = False
        for l in f.readlines():
            if l.startswith("                ************************"):
                trigger = True
            elif trigger and l.startswith(virus_classes):
                l_split = l.split()
                motif_start = int(l_split[1])
                sequence = l_split[2].replace(".", "").upper()
                motif_end = int(l_split[3])
                #print(seq_dict)
                for seq in seq_dict.keys(): ### AAAAAAA
                    if sequence in seq:
                        virus_class, id = seq_dict[seq].split("-")
                d[virus_class][id] = (motif_start, motif_end)
            elif trigger and l.startswith(" "):
                break
        for virus_class in virus_classes:
            mega_dict[virus_class][site] = d[virus_class]
    for virus_class in virus_classes:
        meme_sites = mega_dict[virus_class]
        draw_lineplots(df.loc[df["class"] == virus_class],
                       extra_bases_roi,
                       f"{meme_output}/GLAM2_{virus_class}.png", subopt_mode=True, meme_sites=meme_sites)